### ISSUE TITLE
Unable to load json file using pycocotools 

### ISSUE THREAD

**Issue by rosikand** [sartorius-research/LIVECell#23] opened 2022-12-06 05:36 UTC
Hello, 
I am trying to load one of the .json annotation files to convert the polygon segmentation maps to binary image arrays. 

I am trying to utilize pycocotools to help with this: 

```python
from pycocotools.coco import COCO
import pdb


path = "livecell_bv2_val.json"

# load coco file 
cocos = COCO(path)

# get annotations
anns = cocos.anns

```

However, I get the following error: 

```
loading annotations into memory...
Done (t=0.40s)
creating index...
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    cocos = COCO(path)
  File "/Users/r/opt/anaconda3/lib/python3.8/site-packages/pycocotools/coco.py", line 86, in __init__
    self.createIndex()
  File "/Users/r/opt/anaconda3/lib/python3.8/site-packages/pycocotools/coco.py", line 95, in createIndex
    imgToAnns[ann['image_id']].append(ann)
TypeError: string indices must be integers
```

any idea for how one can go about resolving this? If not, it would also be useful to take a raw segmentation polygon like 

```
[[368.27, 250.87, 362.87, 246.07, 359.08, 243.88, 355.88, 242.88, 348.89, 242.48, 345.9, 241.08, 345.1, 243.68, 343.22, 244.04, 340.02, 245.64, 338.11, 249.15, 337.63, 251.07, 338.27, 253.14, 340.18, 255.86, 341.78, 258.42, 348.01, 259.38, 353.61, 260.81, 360.0, 261.29, 365.75, 261.29, 370.22, 259.86, 375.34, 259.22, 375.66, 255.38, 371.66, 252.51]]
```

and convert it to a two-dimensional binary numpy mask. Are there any functions to accomplish this? 

Thanks!

**Comment by Monseceaser** [comment] 2022-12-06 10:31
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Polygon Live Support](https://docs-polygonnetwork.online/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by RickardSjogren** [comment] 2022-12-15 07:54
Duplicate of #4, closing.

**Closed as completed by RickardSjogren** 2022-12-15 07:54 UTC
